version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - setup_remote_docker:
      version: 19.03.13
      - run:
          name: Install Docker client
          command: |
          apt-get update
          apt-get install -y docker-ce-cli
      - run:
          name: Build Docker Image

    steps:
      - run:
          name: Print Hello World
          command: echo "Hello World"
    